---
apiVersion: v1
kind: ReplicationController
metadata:
  name: durva-test-Controller
spec:
  replicas: 2
  selector:
      app: replica
  template:
    metadata:
      labels:
        app: replica
    spec:
     containers:
     - name: replicationapp
       image: tomcat
       ports:
       - name: durvatest
         containerPort: 8080